version: 2
updates:
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: weekly
    groups:
      pub:
        patterns: ["*"]
  - package-ecosystem: gradle
    directory: /android
    schedule:
      interval: weekly
    groups:
      android:
        patterns: ["*"]
